### PR TITLE
Add FOSDEM 2019.

### PR DESCRIPTION
**Pull request by jonsger**
Hi,

the data for the FOSDEM 2019. The banner is slightly different, but shouldn't be a problem.

Jonathan

### CODE REVIEW

**Comment by loomchild** [comment]
Hi, thanks a lot for contributing! I wasn't aware that the project is still being used. I will try do build and test it this weekend.

BTW, I have a project that is loosely based on this one - Sojourner Web (https://sojourner.loomchild.net). Obviously it requires much more powerful phone than N900. I will also update to FOSDEM 2019 soon.

**Comment by jonsger** [comment]
I setted up the vagrant box from https://github.com/silvio/vagrant-n900-sdk and built successful a debian package out of this branch. Then I installed the package on my N900 and it works fine for FOSDEM2019.

I attached the resulted debian package and made a ZIP file in order to upload it: [sojourner_0.3.7_all.deb.zip](https://github.com/loomchild/sojourner/files/2760095/sojourner_0.3.7_all.deb.zip)

P.S: I accidentally wrote 0.3.9 as version to the debian changelog. I fixed that and forced pushed to this PR.

**Comment by loomchild** [comment]
Thanks a lot. I will look into this today. I will rebuild the package, since I need the source package for the release. I will also create it after merging to master.

**Comment by loomchild** [comment]
I have deployed it in official testing repo (version 0.3.7). Could you tell me if it's working for you (I will check it this evening, once I get hold of my N900).

**Comment by loomchild** [comment]
See http://maemo.org/packages/view/sojourner/ for package details.

**Comment by jonsger** [comment]
I tested it and it works like a charm. Thanks! The update even survived my favourites :)

**Comment by loomchild** [comment]
Thanks! Yes, I take special care to not lose your data by storing it by event ID, since it can get very annoying to spend hours choosing talks and then losing it all:)

Have fun at FOSDEM! I might take my old N900 there as well in addition to using the web version.

**Pull request merged**
