### PR TITLE
Fosdem-2017

### PR DESCRIPTION
**Pull request by bircoph**
Hi!

This PR add Fosdem-2017 schedule and updates banner.

### CODE REVIEW

**Comment by loomchild** [comment]
Hi,

Thanks a lot for contributing!

Two things:

1. I think you forgot to add fosdem2017 resources in setup.py file. Feel free to also update the CHANGELOG (I think it's required to publish a new version in repo).

2. Did you already have a chance to test if these changes work on N900? I didn't use mine for a while, I will try to test it at the beginning of the week.

Thanks again for your help and see you at FOSDEM.

**Comment by bircoph** [comment]
> I think you forgot to add fosdem2017 resources in setup.py file. Feel free to also update the CHANGELOG (I think it's required to publish a new version in repo).

Done. I also bumped version in __init.py__

> Did you already have a chance to test if these changes work on N900?

Yes. It works fine. However, I don't have a deployed N900 SDK environment right now, so I don't have a deb package. Instead I installed 0.3.3 from the repo and copied new/modified files to a live filesystem:
conferences/fosdem2017/*
sojourner.cfg

**Comment by loomchild** [comment]
Could you rebase on master please? I had some local commits that I needed to push, because in fact version 0.3.4 was already released. 

In the meantime I will test the deb with your changes - I have the SDK installed in Vagrant, as described in README.md.

**Comment by loomchild** [comment]
.deb seems to work correctly - I just couldn't validate it completely since I don't have WiFi here - will do it in the evening. 

I will also try to resolve this conflict, but I am not sure how, since I don't have rights to your forked repo. 

AFAIK the changes are only in:
- debian/changelog - your changes belong to 0.3.5.
- __init__.py - version to 0.3.5

**Comment by loomchild** [comment]
Fixed and merged manually. Tested.

Thanks a lot for contributing - I will try to release ASAP.

**Comment by loomchild** [comment]
Uploaded, the package should be available in extras-devel soon. (see http://maemo.org/packages/view/sojourner/ for details, however, this website is updated after a couple of hours, the package should be in repo much sooner).

**Comment by loomchild** [comment]
Package is in extras-devel, I downloaded, tested and promoted it, it should be in extras-testing very soon.

**Pull request closed without merging**
